const data ={
    products: [

        {
            _id:"1",
            name:'Red Dress ',
            category: 'dress',
            image: '/images/brand4.jpg',
            price: 70,
            countInStock: 10,
            brand: 'Holister',
            rating: 5,
            numReviews: 10,
            description:'high quality product',
        },
         
        {
            _id:"2",
            name:'Color T-Shirt',
            category: 'shirts',
            image: '/images/brand9.jpg',
            price: 50,
            countInStock: 10,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description:'high quality product',
        },
         
        {
            _id:"3",
            name:'Grey pants ',
            category: 'pants',
            image: '/images/brand2.jpg',
            price: 130,
            countInStock: 10,
            brand: 'H&M',
            rating: 3.5,
            numReviews: 10,
            description:'high quality product',
        },
         
        {
            _id:"4",
            name:'white T-shirt',
            category: 'shirts',
            image: '/images/brand3.jpg',
            price: 70,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
         
        {
            _id:"5 ",
            name:'White Blouse',
            category: 'shirts',
            image: '/images/brand6.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:"6 ",
            name:'White Blouse',
            category: 'shirts',
            image: '/images/brand8.jpg',
            price: 100,
            countInStock: 10,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:"4",
            name:'white T-shirt',
            category: 'shirts',
            image: '/images/fbrand.jpg',
            price: 70,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:"3",
            name:'Grey pants ',
            category: 'pants',
            image: '/images/fashion.jpg',
            price: 130,
            countInStock: 10,
            brand: 'H&M',
            rating: 3.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:"4",
            name:'white T-shirt',
            category: 'shirts',
            image: '/images/branddd.jpg',
            price: 75,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
      
    ],
};
export default data; 